services:
  - type: web
    name: maybank-trading-platform
    env: node
    buildCommand: yarn && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.18.0
      - key: USE_SQLITE
        value: false
      - key: POSTGRES_URL
        fromDatabase:
          name: maybank-db
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: maybank-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: maybank-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: maybank-db
          property: password
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: maybank-db
          property: database
    
  - type: postgres
    name: maybank-db
    ipAllowList: []
    plan: free