services:
  - type: web
    name: maybank-trading-platform
    env: node
    buildCommand: yarn && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.18.0
      - key: USE_SQLITE
        value: false
      - key: POSTGRES_URL
        value: postgresql://oeasy:mKEagGR9ld5yuLWSvBuwhXrGVVVc9nay@dpg-d39v2l3uibrs73f6stk0-a.singapore-postgres.render.com/oeasy
      - key: POSTGRES_HOST
        value: dpg-d39v2l3uibrs73f6stk0-a.singapore-postgres.render.com
      - key: POSTGRES_USER
        value: oeasy
      - key: POSTGRES_PASSWORD
        value: mKEagGR9ld5yuLWSvBuwhXrGVVVc9nay
      - key: POSTGRES_DATABASE
        value: oeasy